users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
    path('profile/<int:pk>/', views.ProfileView.as_view(), name='profile'),
    path('change_password/', views.change_password, name='change_password'),
    path('subscribe/<int:pk>/', views.SubscribeView.as_view(), name='subscribe'),
    path('feedback/', views.FeedbackView.as_view(), name='feedback'),
    path('<int:pk>/collect_videos/', views.CollectListView.as_view(), name='collect_videos'),
    path('<int:pk>/like_videos/', views.LikeListView.as_view(), name='like_videos'),
]

video/urls.py
from django.urls import path
from . import views

app_name = 'video'
urlpatterns = [
    path('index', views.IndexView.as_view(), name='index'),
    path('search/', views.SearchListView.as_view(), name='search'),
    path('detail/<int:pk>/', views.VideoDetailView.as_view(), name='detail'),
    path('like/', views.like, name='like'),
    path('collect/', views.collect, name='collect'),
]

videoproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from video import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('video/',include('video.urls')),
    path('myadmin/', include('myadmin.urls')),
    path('users/',include('users.urls')),
    path('comment/',include('comment.urls')),
    path('', views.IndexView.as_view(), name='home'), # 默认首页

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models



class User(AbstractUser):
    GENDER_CHOICES = (
        ('M', '男'),
        ('F', '女'),
    )
    nickname = models.CharField(blank=True, null=True, max_length=20)
    avatar = models.FileField(upload_to='avatar/')
    mobile = models.CharField(blank=True, null=True, max_length=13)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES,blank=True, null=True)
    subscribe = models.BooleanField(default=False)

    class Meta:
        db_table = "v_user"


class Feedback(models.Model):
    contact = models.CharField(blank=True, null=True, max_length=20)
    content = models.CharField(blank=True, null=True, max_length=200)
    timestamp = models.DateTimeField(auto_now_add=True, null=True)

    class Meta:
        db_table = "v_feedback"

templates/base/base.html
{% load static %}
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="description" content="基于Django的视频点播网站">
    <meta name="google-site-verification" content="UhrjUG70pwiY6Sp4u4p5Q3ol8iD7yx4ZSwmGBpoaWik" />
    <link rel="icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
    <title>视点</title>

    <link rel="stylesheet" type="text/css" href="https://cdn.staticfile.org/semantic-ui/2.4.1/semantic.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/semantic.custom.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% block css %}{% endblock css %}

    <script>
    var _hmt = _hmt || [];
    (function() {
      var hm = document.createElement("script");
      hm.src = "https://hm.baidu.com/hm.js?e3be3decd24d944e0bc592558617d210";
      var s = document.getElementsByTagName("script")[0];
      s.parentNode.insertBefore(hm, s);
    })();
    </script>

</head>
<body>

{% include "base/header.html" %}
<div class="ui container" id="v-content">
    {% block content %}
    {% endblock content %}
</div>
{% include "base/footer.html" %}

<script src="https://cdn.staticfile.org/jquery/1.9.0/jquery.min.js"></script>
<script src="https://cdn.staticfile.org/semantic-ui/2.4.1/semantic.min.js"></script>
<script>
    var search_url = "{% url 'video:search' %}"
</script>
<script src="{% static 'js/header.js' %}"></script>

{% block javascript %}
{% endblock javascript %}

{% block modal %}
{% endblock modal %}

</body>
</html>

templates/base/footer.html
{% load static %}

<div class="ui vertical footer segment ">
    <div class="ui center aligned container">
        <div class="ui divider"></div>
        <img src="{% static 'img/logo.png' %}" class="ui centered mini image">
        <div class="ui horizontal   small divided link list">
            <a class="item" href="#">北京堆栈科技有限公司</a>
            <a class="item" href="#">联系我们</a>
            <a class="item" href="#">京ICP证090287</a>
        </div>
    </div>
</div>

templates/base/form_errors.html
{% if form.errors %}
<div class="ui info message">
    <ul class="list">

        {% for field in form %}
        {% for error in field.errors %}
        <li class="item">{{ error|escape }}</li>
        {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
        <li class="item">{{ error|escape }}</li>
        {% endfor %}
    </ul>
</div>

{% endif %}

templates/base/form_messages.html
{% if messages %}
<div class="ui info message">
    {% for message in messages %}
    <div class="item">{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

templates/base/header.html
{% load static %}
{% load thumbnail %}

<div class="ui sticky fixed  menu">
    <div class="ui container">
        <a href="/" class="borderless header item">
            <img class="logo" src="{% static 'img/logo.png' %}">
            视点
        </a>
        <div class="v-header-extra">
            <div class="ui small icon input v-video-search">
                <input class="prompt" value="{{ q }}" type="text" placeholder="搜索视频" id="v-search">
                <i id="search" class="search icon" style="cursor:pointer;"></i>
            </div>

            {% if user.is_authenticated %}
            <div class="ui inline dropdown" id="v-header-avatar" style="">
                <div class="" style="display:inline-block;font-weight:bold;">
                    {% thumbnail user.avatar "200x200" crop="center" as im %}
                    <img class="ui avatar image" src="{{ im.url }}">
                    {% empty %}
                    <img class="ui avatar image" src="{% static 'img/img_default_avatar.png' %}">
                    {% endthumbnail %}
                    {{ user.username }}
                </div>
                <i class="dropdown icon"></i>
                <div class="menu">
                    <div class="item" onclick="window.location='{% url 'users:profile' user.pk %}';">
                        <i class="user icon"></i>
                        <span>个人资料</span>
                    </div>
                    <div class="item" onclick="window.location='{% url 'users:collect_videos' user.pk %}';">
                        <i class="bookmark icon"></i>
                        <span>我的收藏</span>
                    </div>
                    <div class="item" onclick="window.location='{% url 'users:like_videos' user.pk %}';">
                        <i class="heart icon"></i>
                        <span>我的喜欢</span>
                    </div>
                    <div class="item" onclick="window.location='{% url 'users:logout' %}';">
                        <i class="sign-out icon"></i>
                        <span>退出</span>
                    </div>
                </div>
            </div>
            {% else %}
            <a class="ui tiny secondary basic button" id="v-header-login" href="{% url 'users:login' %}?next={{ request.path }}">登录</a>
            {% endif %}

        </div>
    </div>
</div>

templates/base/left_nav.html
<div class="ui secondary vertical pointing menu">
    <a id="id_profile" class="link item" href="{% url 'users:profile' user.pk %}">
        <i class="grey user icon"></i>
        <span class="v-nav-title">个人资料</span>
    </a>
    <a id="id_password" class="link item" href="{% url 'users:change_password' %}">
        <i class="grey edit icon"></i>
        <span class="v-nav-title">修改密码</span>
    </a>
    <a id="id_subscribe" class="link item" href="{% url 'users:subscribe' user.pk %}">
        <i class="grey rss icon"></i>
        <span class="v-nav-title">订阅设置</span>
    </a>
    <a id="id_feedback" class="link item" href="{% url 'users:feedback' %}">
        <i class="grey list icon"></i>
        <span class="v-nav-title">反馈与建议</span>
    </a>
</div>

templates/base/page_nav.html
{% if is_paginated %}
<div class="video-page">
    <div class="ui circular labels">
        {% if page_obj.has_previous %}
        <a class="ui circular label" href="?page={{ page_obj.previous_page_number }}{% if c %}&c={{c}}{% endif %}{% if q %}&q={{q}}{% endif %}">&lt;</a>
        {% endif %}
        {% for i in page_list %}
        {% if page_obj.number == i %}
        <a class="ui red circular label">{{ i }}</a>
        {% else %}
        <a class="ui circular label" href="?page={{ i }}{% if c %}&c={{c}}{% endif %}{% if q %}&q={{q}}{% endif %}">{{ i }}</a>
        {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
        <a class="ui circular label" href="?page={{ page_obj.next_page_number }}{% if c %}&c={{c}}{% endif %}{% if q %}&q={{q}}{% endif %}">&gt;</a>
        {% endif %}
    </div>
</div>
{% endif %}