comment/urls.py
from django.urls import path

from . import views

app_name = 'comment'
urlpatterns = [
    path('submit_comment/<int:pk>',views.submit_comment, name='submit_comment'),
    path('get_comments/', views.get_comments, name='get_comments'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
    path('profile/<int:pk>/', views.ProfileView.as_view(), name='profile'),
    path('change_password/', views.change_password, name='change_password'),
    path('subscribe/<int:pk>/', views.SubscribeView.as_view(), name='subscribe'),
    path('feedback/', views.FeedbackView.as_view(), name='feedback'),
    path('<int:pk>/collect_videos/', views.CollectListView.as_view(), name='collect_videos'),
    path('<int:pk>/like_videos/', views.LikeListView.as_view(), name='like_videos'),
]

video/urls.py
from django.urls import path
from . import views

app_name = 'video'
urlpatterns = [
    path('index', views.IndexView.as_view(), name='index'),
    path('search/', views.SearchListView.as_view(), name='search'),
    path('detail/<int:pk>/', views.VideoDetailView.as_view(), name='detail'),
    path('like/', views.like, name='like'),
    path('collect/', views.collect, name='collect'),
]

videoproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from video import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('video/',include('video.urls')),
    path('myadmin/', include('myadmin.urls')),
    path('users/',include('users.urls')),
    path('comment/',include('comment.urls')),
    path('', views.IndexView.as_view(), name='home'), # 默认首页

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

video/models.py
import os

from django.conf import settings
from django.db import models
from django.dispatch import receiver


class VideoQuerySet(models.query.QuerySet):

    def get_count(self):
        return self.count()

    def get_published_count(self):
        return self.filter(status=0).count()

    def get_not_published_count(self):
        return self.filter(status=1).count()

    def get_published_list(self):
        return self.filter(status=0).order_by('-create_time')

    def get_search_list(self, q):
        if q:
            return self.filter(title__contains=q).order_by('-create_time')
        else:
            return self.order_by('-create_time')

    def get_recommend_list(self):
        return self.filter(status=0).order_by('-view_count')[:4]


class Classification(models.Model):
    list_display = ("title",)
    title = models.CharField(max_length=100,blank=True, null=True)
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    class Meta:
        db_table = "v_classification"

class Video(models.Model):
    STATUS_CHOICES = (
        ('0', '发布中'),
        ('1', '未发布'),
    )
    title = models.CharField(max_length=100,blank=True, null=True)
    desc = models.CharField(max_length=255,blank=True, null=True)
    classification = models.ForeignKey(Classification, on_delete=models.CASCADE, null=True)
    file = models.FileField(max_length=255)
    cover = models.ImageField(upload_to='cover/',blank=True, null=True)
    status = models.CharField(max_length=1 ,choices=STATUS_CHOICES, blank=True, null=True)
    view_count = models.IntegerField(default=0, blank=True)
    liked = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                   blank=True, related_name="liked_videos")
    collected = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                   blank=True, related_name="collected_videos")
    create_time = models.DateTimeField(auto_now_add=True, blank=True, max_length=20)

    objects = VideoQuerySet.as_manager()
    class Meta:
        db_table = "v_video"

    def increase_view_count(self):
        self.view_count += 1
        self.save(update_fields=['view_count'])

    def switch_like(self, user):
        if user in self.liked.all():
            self.liked.remove(user)
        else:
            self.liked.add(user)

    def count_likers(self):
        return self.liked.count()

    def user_liked(self, user):
        if user in self.liked.all():
            return 0
        else:
            return 1

    def switch_collect(self, user):
        if user in self.collected.all():
            self.collected.remove(user)

        else:
            self.collected.add(user)

    def count_collecters(self):
        return self.collected.count()

    def user_collected(self, user):
        if user in self.collected.all():
            return 0
        else:
            return 1


@receiver(models.signals.post_delete, sender=Video)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """
    删除FileField文件
    """
    if instance.file:
        if os.path.isfile(instance.file.path):
            os.remove(instance.file.path)

video/forms.py
from django import forms
from comment.models import Comment

class CommentForm(forms.ModelForm):
    content = forms.CharField(error_messages={'required': '不能为空',},
        widget=forms.Textarea(attrs = {'placeholder': '请输入评论内容' })
    )

    class Meta:
        model = Comment
        fields = ['content']

video/views.py
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.views import generic
from django.views.decorators.http import require_http_methods

from helpers import get_page_list, ajax_required
from .forms import CommentForm
from .models import Video, Classification


class IndexView(generic.ListView):
    model = Video
    template_name = 'video/index.html'
    context_object_name = 'video_list'
    paginate_by = 12
    c = None

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        paginator = context.get('paginator')
        page = context.get('page_obj')
        page_list = get_page_list(paginator, page)
        classification_list = Classification.objects.filter(status=True).values()
        context['c'] = self.c
        context['classification_list'] = classification_list
        context['page_list'] = page_list
        return context

    def get_queryset(self):
        self.c = self.request.GET.get("c", None)
        if self.c:
            classification = get_object_or_404(Classification, pk=self.c)
            return classification.video_set.all().order_by('-create_time')
        else:
            return Video.objects.filter(status=0).order_by('-create_time')


class SearchListView(generic.ListView):
    model = Video
    template_name = 'video/search.html'
    context_object_name = 'video_list'
    paginate_by = 8
    q = ''

    def get_queryset(self):
        self.q = self.request.GET.get("q", "")
        return Video.objects.filter(title__contains=self.q).filter(status=0)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(SearchListView, self).get_context_data(**kwargs)
        paginator = context.get('paginator')
        page = context.get('page_obj')
        page_list = get_page_list(paginator, page)
        context['page_list'] = page_list
        context['q'] = self.q
        return context


class VideoDetailView(generic.DetailView):
    model = Video
    template_name = 'video/detail.html'

    def get_object(self, queryset=None):
        obj = super().get_object()
        obj.increase_view_count()
        return obj

    def get_context_data(self, **kwargs):
        context = super(VideoDetailView, self).get_context_data(**kwargs)
        form = CommentForm()
        recommend_list = Video.objects.get_recommend_list()
        context['form'] = form
        context['recommend_list'] = recommend_list
        return context

@ajax_required
@require_http_methods(["POST"])
def like(request):
    if not request.user.is_authenticated:
        return JsonResponse({"code": 1, "msg": "请先登录"})
    video_id = request.POST['video_id']
    video = Video.objects.get(pk=video_id)
    user = request.user
    video.switch_like(user)
    return JsonResponse({"code": 0, "likes": video.count_likers(), "user_liked": video.user_liked(user)})


@ajax_required
@require_http_methods(["POST"])
def collect(request):
    if not request.user.is_authenticated:
        return JsonResponse({"code": 1, "msg": "请先登录"})
    video_id = request.POST['video_id']
    video = Video.objects.get(pk=video_id)
    user = request.user
    video.switch_collect(user)
    return JsonResponse({"code": 0, "collects": video.count_collecters(), "user_collected": video.user_collected(user)})

templates/video/ad.html
{% load static %}

<a target="_blank" href="https://promotion.aliyun.com/ntms/act/enterprise-discount.html?userCode=3bcjya8p">
    <img src="{% static 'img/img_ad_banner.jpg' %}">
</a>

templates/video/detail.html
{% extends 'base/base.html' %}
{% load static %}
{% load video_tag %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/dropload.css' %}">
{% endblock css %}

{% block content %}
<div class="ui unstackable two column grid">
    <div class=" ten wide column">
        <video class="video" autoplay="autoplay" controls="controls" controlslist="nodownload"
               disablePictureInPicture>
            <source src="{{video.file.url}}" type="video/mp4">
        </video>
        <div class="video-info">
            <div class="video-title">{{ video.title }}</div>
            <div class="video-view-count">{{ video.view_count }}次观看</div>
            <div class="video-view-operation">
                {{video.desc}}
            </div>
            <div class="extra content video-view-operation">
                <span class="left floated like">
                    <i class="like {%  user_liked_class video user %} icon cursor" id="like"
                       video-id="{{ video.id }}"></i>
                    <span id="like-count">{{ video.count_likers }}</span>
                </span>
                <span class="right floated star">
                    <i class="bookmark {%  user_collected_class video user %}  icon cursor" id="star"
                       video-id="{{ video.id }}"></i>
                    <span id="collect-count">{{ video.count_collecters }}</span>
                </span>
            </div>
            <div class="ui divider"></div>
        </div>
        <div class="ui comments">
            {% if user.is_authenticated %}
            <form class="ui reply form" id="comment_form" method="post"
                  action="{% url 'comment:submit_comment' video.pk %}">
                {% csrf_token %}
                <div class="field">
                    {{form.content}}
                    <input type="hidden" value="{{ video.id }}" name="video_id">
                </div>
                <button class="ui primary button" type="submit">
                    添加评论
                </button>
                <div class="ui info message n">
                    <div class="item" id="comment-result"></div>
                </div>
            </form>
            {% else %}
            <div class="ui ignored info attached message">
                <p>登录后即可评论 &nbsp;&nbsp;&nbsp;<a href="{% url 'users:login' %}?next={{ request.path }}">马上登录</a></p>
            </div>
            {% endif %}
            <h3 class="ui dividing header" id="id_comment_label">评论</h3>
            <div class="comment-list"></div>
        </div>
    </div>
    <div class="six wide column">
        {% include "video/recommend.html" %}
        {% include "video/ad.html" %}
    </div>
</div>
{% endblock content %}

{% block javascript %}

<script>
var comments_url = "{% url 'comment:get_comments' %}"
var video_id = {{ video.id }}
</script>

<script src="{% static 'js/dropload.js' %}"></script>
<script src="{% static 'js/load_comments.js' %}"></script>
<script src="{% static 'js/detail.js' %}"></script>
{% endblock javascript %}
 

templates/video/index.html
{% extends 'base/base.html' %}
{% load static %}
{% load thumbnail %}
{% load video_tag %}

{% block content %}

<div class="classification">
    <a class="ui {% if c %}{% else %}red{% endif %} label" href="{% url 'home' %}">全部</a>
    {% for item in classification_list %}
    <a class="ui {% if c == item.id|stringformat:'s' %}red{% endif %} label" href="?c={{ item.id }}">{{ item.title }}</a>
    {% endfor %}
</div>

<div class="ui hidden divider"></div>
<div class="ui grid">
    {% for item in video_list %}
    <div class="four wide column">
        <div class="ui card">
            <a class="image" href="{% url 'video:detail' item.pk %}">
                {% thumbnail item.cover "300x200" crop="center" as im %}
                <img class="ui image" src="{{ im.url }}">
                {% empty %}
                {% endthumbnail %}
                <i class="large play icon v-play-icon"></i>
            </a>
            <div class="content">
                <a class="header" href="{% url 'video:detail' item.pk %}">{{ item.title }}</a>
                <div class="meta">
                    <span class="date">发布于{{ item.create_time|time_since}}</span>
                </div>
                <div class="description">
                    {{ item.view_count}}次观看
                </div>
            </div>
        </div>
    </div>
    {% empty %}
    <h3>暂无数据</h3>
    {% endfor %}
</div>

{% include "base/page_nav.html" %}

{% endblock content %}

templates/video/recommend.html
{% load thumbnail %}

<span class="video-side-title">推荐列表</span>
<div class="ui unstackable divided items">

    {% for item in recommend_list %}
    <div class="item">
        <div class="ui tiny image">
            {% thumbnail item.cover "300x200" crop="center" as im %}
            <img class="ui image" src="{{ im.url }}">
            {% empty %}
            {% endthumbnail %}
        </div>
        <div class="middle aligned content">
            <a class=" header-title" href="{% url 'video:detail' item.pk %}">{{ item.title }}</a>
            <div class="meta">
                <span class="description">{{ item.view_count }}次观看</span>
            </div>
        </div>
    </div>
    {% empty %}
    <h3>暂无推荐</h3>
    {% endfor %}

</div>

templates/video/search.html
{% extends 'base/base.html' %}
{% load static %}
{% load thumbnail %}

{% block content %}

<h3 class="ui header">搜索结果</h3>
<div class="ui unstackable items">

    {% for item in video_list %}
    <div class="item">
        <div class="ui tiny image">
            {% thumbnail item.cover "300x200" crop="center" as im %}
            <img class="ui image" src="{{ im.url }}">
            {% empty %}
            {% endthumbnail %}
        </div>
        <div class="middle aligned content">
          <a class="header" href="{% url 'video:detail' item.pk %}">{{ item.title }}</a>
        </div>
    </div>
    {% empty %}
    <h3>暂无数据</h3>
    {% endfor %}

</div>

{% include "base/page_nav.html" %}


{% endblock content %}

{% block javascript %}
<script  type="text/javascript" >
$('.ui .dropdown').dropdown();
</script>
{% endblock javascript %}